name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
    
    - name: Upload Library
      uses: actions/upload-artifact@v2
      with:
        name: HandBrake-x86_64-Win_GUI-EXE
        path: LightController/bin/Debug

    - name: Upload Demo Project
      uses: actions/upload-artifact@v2
      with:
        name: HandBrake-x86_64-Win_GUI-EXE
        path: LightController.Win.Demo/bin/Debug
    
